; ======================= T_BEAM SX1262 Frequency Variants ===============================;

[env:T_BEAM_SX1262_433MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1262
    -D CONFIG_RADIO_FREQ=433.0

[env:T_BEAM_SX1262_868MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1262
    -D CONFIG_RADIO_FREQ=868.0

[env:T_BEAM_SX1262_915MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1262
    -D CONFIG_RADIO_FREQ=915.0

[env:T_BEAM_SX1262_920MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1262
    -D CONFIG_RADIO_FREQ=920.0

; ======================= T_BEAM SX1276 Frequency Variants ===============================;

[env:T_BEAM_SX1276_868MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1276
    -D CONFIG_RADIO_FREQ=868.0

[env:T_BEAM_SX1276_915MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1276
    -D CONFIG_RADIO_FREQ=915.0

[env:T_BEAM_SX1276_920MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1276
    -D CONFIG_RADIO_FREQ=920.0

; ======================= T_BEAM SX1278 Frequency Variants ===============================;

[env:T_BEAM_SX1278_433MHZ]
extends = esp32_psram
board = esp32dev
build_flags = 
    ${esp32_psram.build_flags}
    -D T_BEAM_SX1278
    -D CONFIG_RADIO_FREQ=433.0

; ======================= T_BEAM S3 SUPREME SX1262 Frequency Variants ===============================;

[env:T_BEAM_S3_SUPREME_SX1262_433MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_SX1262
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=433.0

[env:T_BEAM_S3_SUPREME_SX1262_868MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_SX1262
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=868.0

[env:T_BEAM_S3_SUPREME_SX1262_915MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_SX1262
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=915.0

[env:T_BEAM_S3_SUPREME_SX1262_920MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_SX1262
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=920.0

; ======================= T_BEAM S3 SUPREME LR1121 Frequency Variants ===============================;

[env:T_BEAM_S3_SUPREME_LR1121_433MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_LR1121
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=433.0

[env:T_BEAM_S3_SUPREME_LR1121_868MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_LR1121
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=868.0

[env:T_BEAM_S3_SUPREME_LR1121_915MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_LR1121
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=915.0

[env:T_BEAM_S3_SUPREME_LR1121_920MHZ]
extends = esp32s3
board = t-beams3-supreme
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_S3_SUPREME_LR1121
    -DBOARD_HAS_PSRAM
    -D CONFIG_RADIO_FREQ=920.0

; ======================= T_BEAM 1W SX1262 Frequency Variants ===============================;

[env:T_BEAM_1W_SX1262_433MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_SX1262
    -D CONFIG_RADIO_FREQ=433.0

[env:T_BEAM_1W_SX1262_868MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_SX1262
    -D CONFIG_RADIO_FREQ=868.0

[env:T_BEAM_1W_SX1262_915MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_SX1262
    -D CONFIG_RADIO_FREQ=915.0

[env:T_BEAM_1W_SX1262_920MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_SX1262
    -D CONFIG_RADIO_FREQ=920.0

; ======================= T_BEAM 1W LR1121 Frequency Variants ===============================;

[env:T_BEAM_1W_LR1121_433MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR1121
    -D CONFIG_RADIO_FREQ=433.0

[env:T_BEAM_1W_LR1121_868MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR1121
    -D CONFIG_RADIO_FREQ=868.0

[env:T_BEAM_1W_LR1121_915MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR1121
    -D CONFIG_RADIO_FREQ=915.0

[env:T_BEAM_1W_LR1121_920MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR1121
    -D CONFIG_RADIO_FREQ=920.0

; ======================= T_BEAM 1W LR2021 Frequency Variants ===============================;

[env:T_BEAM_1W_LR2021_433MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR2021
    -D CONFIG_RADIO_FREQ=433.0

[env:T_BEAM_1W_LR2021_868MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR2021
    -D CONFIG_RADIO_FREQ=868.0

[env:T_BEAM_1W_LR2021_915MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR2021
    -D CONFIG_RADIO_FREQ=915.0

[env:T_BEAM_1W_LR2021_920MHZ]
extends = esp32s3
board = ESP32-S3-WROOM-1-N16R8
build_flags = 
    ${esp32s3.build_flags}
    -D T_BEAM_1W_LR2021
    -D CONFIG_RADIO_FREQ=920.0

